name: CI with GitHub Actions using Maven and JUnit | © 2023 by minhchan


on:
  push:
  pull_request:
    branches: [ main ]

jobs: 

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Check-out repository 
        uses: actions/checkout@v3

      - name: Set up JDK 20 
        uses: actions/setup-java@v3 
        with:
          java-version: '20' 
          distribution: 'temurin'
          cache: maven
     
      - name: Build project with Maven
        run: mvn -B package --file Backend/ShoesCustom/ShoesPee/ShoesPee/pom.xml
      
      # - name: Distribute jar-war file 
      #   run: mkdir staging && cp out/artifacts/shoe_stylise_jar/*.jar staging     
     
      # - name: Make hyperlink to jar-war file 
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: shoe-stylise.jar
      #     path: staging


