name: CI/CD 


on:
  push:
  pull_request:
    branches: [ main ]

jobs: 

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Check-out repository 
        uses: actions/checkout@v3

      - name: Set up JDK 20 
        uses: actions/setup-java@v3 
        with:
          java-version: '20' 
          distribution: 'adopt'
          cache: maven
     
      - name: Build project with Maven
        run: mvn -B package --file Backend/ShoesCustom/ShoesPee/ShoesPee/pom.xml


      
      # - name: Distribute jar-war file 
      #   run: mkdir staging && cp target/*.jar staging     
     
      # - name: Make hyperlink to jar-war file 
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: 0.0.1-SNAPSHOT.jar  
      #     path: staging
      
      # - name: Build & push Docker image
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: minhchan/minhchan-shoepee
      #     tags: latest
      #     registry: registry-1.docker.io
      #     dockerfile: Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}


  
